set(INCLUDE_DEBUG_FEATURES FALSE)
set(TARGET_PLATFORM PICO_RP2040)

if (CMAKE_BUILD_TYPE STREQUAL Debug)
    set(INCLUDE_DEBUG_FEATURES TRUE)
    add_compile_definitions(INCLUDE_DEBUG_FEATURES=1)
elseif(CMAKE_BUILD_TYPE STREQUAL Host)
    set(TARGET_PLATFORM HOST)
    add_compile_definitions(BUILD_FOR_HOST=1)
endif()

set(PREVIOUS_CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE} CACHE FILEPATH "")

if ((NOT ${PREVIOUS_CMAKE_BUILD_TYPE} STREQUAL ${CMAKE_BUILD_TYPE}) AND
    ((${PREVIOUS_CMAKE_BUILD_TYPE} STREQUAL "Host") OR (${CMAKE_BUILD_TYPE} STREQUAL "Host")))
    message(FATAL_ERROR "Target platform changed, please clear CMake cache")
endif()

message(STATUS "Build configuration")
message(STATUS "  INCLUDE_DEBUG_FEATURES : ${INCLUDE_DEBUG_FEATURES}")
message(STATUS "  TARGET_PLATFORM        : ${TARGET_PLATFORM}")
