# Project configuration
## Application
set(CONFIG_APP_NAME rp2040-study)
set(CONFIG_INCLUDE_DEBUG_FEATURES FALSE)
## Platform
set(CONFIG_TARGET_PLATFORM PICO_RP2040)
## Debug utils
set(CONFIG_SYSVIEW_APP_NAME ${CONFIG_APP_NAME})
set(CONFIG_SYSVIEW_DEVICE_NAME ${CONFIG_TARGET_PLATFORM})
set(CONFIG_SYSVIEW_RAM_BASE 0x10000000)

message(STATUS "Build configuration")
message(STATUS "  CONFIG_INCLUDE_DEBUG_FEATURES : ${CONFIG_INCLUDE_DEBUG_FEATURES}")
message(STATUS "  CONFIG_TARGET_PLATFORM        : ${CONFIG_TARGET_PLATFORM}")
message(STATUS "  CONFIG_SYSVIEW_APP_NAME       : ${CONFIG_SYSVIEW_APP_NAME}")
message(STATUS "  CONFIG_SYSVIEW_DEVICE_NAME    : ${CONFIG_SYSVIEW_DEVICE_NAME}")
message(STATUS "  CONFIG_SYSVIEW_RAM_BASE       : ${CONFIG_SYSVIEW_RAM_BASE}")

if (CMAKE_BUILD_TYPE STREQUAL Debug)
    set(CONFIG_INCLUDE_DEBUG_FEATURES TRUE)
    add_compile_definitions(CONFIG_INCLUDE_DEBUG_FEATURES=1)
elseif(CMAKE_BUILD_TYPE STREQUAL Host)
    set(CONFIG_TARGET_PLATFORM HOST)
    add_compile_definitions(BUILD_FOR_HOST=1)
endif()

set(PREVIOUS_CMAKE_BUILD_TYPE ${CMAKE_BUILD_TYPE} CACHE FILEPATH "")

if ((NOT ${PREVIOUS_CMAKE_BUILD_TYPE} STREQUAL ${CMAKE_BUILD_TYPE}) AND
    ((${PREVIOUS_CMAKE_BUILD_TYPE} STREQUAL "Host") OR (${CMAKE_BUILD_TYPE} STREQUAL "Host")))
    message(FATAL_ERROR "Target platform changed, please clear CMake cache")
endif()
